owner: amarouane-ABDELHAK # GitHub username
repo: ghgc-services-status # GitHub repository name
sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com
assignees: # Users to assign downtime issues (optional)
  - amarouane-ABDELHAK
status-website:
  baseUrl: /ghgc-services-status # where "repo" is your repository name
  name: GHG Status
